title: project
image:
  back: gray-900
  icon: false
  query: false

tabs:
  content:
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                size: medium
              gallery:
                label: Gallery
                type: files
              description:
                label: Description
                type: textarea
                size: medium
              type:
                label: Type
                type: tags
                options:
                  - Lamp
                  - Chair
                  - Shelf
                  - Sofa
                  - Table
                  - Cabinet
                  - Desk
                  - Bench
                width: 1/2
              environment:
                label: Environment 
                type: tags
                width: 1/2
                options:
                  - Interior
                  - Exterior
              itemHeight:
                label: Height (cm)
                type: number
                width: 1/3
              itemDepth:
                label: Depth (cm)
                type: number
                width: 1/3
              itemWidth:
                label: Width (cm)
                type: number
                width: 1/3
              year:
                label: Year
                type: number
                width: 1/2
              price:
                label: Price (eu)
                type: number
                width: 1/2
                  
      - width: 1/3
        sections:
          files:
            label: All files
            type: files

  meta: tabs/seo/meta
